const assert=require('node:assert/strict');
const A=require('../assets/resume-assessment.js');
const p={role:'Data Engineer',experience:'3+ years',education:"Bachelor's degree",skills:['AWS','ETL']};
let a=A.assess(p,"Data Engineer with 2 years of experience building AWS and ETL pipelines. Bachelor's degree.");
assert.equal(a.exp.score,67);assert.equal(a.keywords.score,100);assert.equal(a.qual.score,100);assert.equal(a.overall,90);
a=A.assess(p,"Sales manager with 10 years of experience. Skills: AWS and ETL. Bachelor's degree.");assert.equal(a.exp.years,null);assert.equal(a.exp.score,0);
a=A.assess(p,'Data Engineer with 24 months experience using AWS and ETL.');assert.equal(a.exp.score,67);assert.equal(a.qual.score,0);
a=A.experience(p,'Data Engineer Jan 2022 - Jan 2024 built AWS ETL pipelines',new Date('2026-01-01'));assert.equal(a.years,2);assert.equal(a.score,67);
a=A.experience(p,'Data Engineer Jan 2022 - Jan 2024 AWS ETL\nData Engineer Jan 2023 - Jan 2024 AWS ETL',new Date('2026-01-01'));assert.equal(a.years,2);
a=A.experience(p,'Data Engineer | 05/2023 - 07/2026 | AWS ETL pipelines',new Date('2026-09-29'));assert.equal(a.years,3.2);
a=A.experience(p,'Data Engineer | 2023-05 - Present | AWS ETL pipelines',new Date('2026-09-29'));assert.equal(a.years,3.4);
a=A.experience({role:'Data Engineer I, CMT',experience:'1+ years',skills:['AWS','ETL']},'Data Engineer 03/2026 – Current Deloitte USI\nData Engineer 06/2025 – 02/2026 Tech Mahindra\nData Engineer 09/2024 – 05/2025 Tech Mahindra',new Date('2026-09-29'));assert.equal(a.years,1.9);
assert.equal(A.qualification({education:"Bachelor's or Master's degree"},'B.Tech').score,100);
assert.equal(A.qualification({education:"Master's degree"},'B.Tech').score,0);
assert.equal(A.experience({experience:'Not Specified'},'2 years').score,null);
assert.equal(A.experience({role:'Software Engineer',experience:'Fresher / Entry-level',skills:['Java']},'WORK EXPERIENCE\nSoftware Engineer Intern Jan 2026 - Jun 2026 Java',new Date('2026-09-29')).score,null);
let edu=A.experience(p,'EDUCATION\nB.Tech Computer Science 2020 - 2024\nUniversity\nSkills: AWS ETL',new Date('2026-09-29'));assert.equal(edu.years,null);
let mixed=A.experience(p,'WORK EXPERIENCE\nData Engineer Jan 2025 - Jan 2026 AWS ETL\nEDUCATION\nB.Tech Computer Science 2020 - 2024\nUniversity',new Date('2026-09-29'));assert.equal(mixed.years,1);
let fourYearDegree=A.experience(p,'B.Tech is a 4 years degree. Skills include AWS and ETL.',new Date('2026-09-29'));assert.equal(fourYearDegree.years,null);
console.log('13 assessment regression cases passed');
